Repository neo4j-graphacademy/courses, pull requests merged in 2023-08, with the labels that each got.

#137 Graphql course live
  asciidoc/courses/graphql-basics/course.adoc
  asciidoc/courses/graphql-basics/modules/1-setup/lessons/1-graphql/lesson.adoc
  asciidoc/courses/graphql-basics/modules/1-setup/lessons/2-neo4j-graphql/lesson.adoc
  asciidoc/courses/graphql-basics/modules/1-setup/lessons/3-neo4j-graphql-library/lesson.adoc
  asciidoc/courses/graphql-basics/modules/2-queries/lessons/1-graphql-queries/questions/question-1.adoc
  asciidoc/courses/graphql-basics/modules/2-queries/lessons/1-graphql-queries/questions/question-3.adoc
  asciidoc/courses/graphql-basics/modules/2-queries/lessons/2-graphql-type-definitions/lesson.adoc
  asciidoc/courses/graphql-basics/modules/2-queries/lessons/2-graphql-type-definitions/questions/question-1.adoc
  asciidoc/courses/graphql-basics/modules/2-queries/lessons/2-graphql-type-definitions/questions/question-3.adoc
  asciidoc/courses/graphql-basics/modules/2-queries/lessons/3-graphql-relationships/lesson.adoc
  asciidoc/courses/graphql-basics/modules/2-queries/lessons/3-graphql-relationships/questions/question-1.adoc
  asciidoc/courses/graphql-basics/modules/2-queries/lessons/3-graphql-relationships/questions/question-2.adoc
  asciidoc/courses/graphql-basics/modules/2-queries/lessons/4-add-relationships/lesson.adoc
  asciidoc/courses/graphql-basics/modules/2-queries/lessons/4-add-relationships/sandbox.cypher
  asciidoc/courses/graphql-basics/modules/3-mutations/lessons/2-nested-mutations/questions/question-1.adoc
  asciidoc/courses/graphql-basics/modules/4-configure/_lessons/2-full-text/questions/question-1.adoc
Labels: release

#138 Python app - small fixes and updates
  asciidoc/courses/app-python/modules/0-setup/lessons/1-setup/lesson.adoc
  asciidoc/courses/app-python/modules/1-driver/lessons/3-connecting/lesson.adoc
  asciidoc/courses/app-python/modules/1-driver/lessons/3-connecting/questions/1-test-number.adoc
  asciidoc/courses/app-python/modules/2-interacting/lessons/2-results/lesson.adoc
Labels: update

#143 PDF Summaries
  asciidoc/courses/neo4j-fundamentals/modules/2-property-graphs/lessons/1-property-graph/images/graphs-explained.png
  asciidoc/courses/neo4j-fundamentals/modules/2-property-graphs/lessons/3-rdbms-to-graph/images/orders_graph.png
  asciidoc/courses/neo4j-fundamentals/modules/2-property-graphs/lessons/3-rdbms-to-graph/images/orders_rdbms.png
  asciidoc/courses/neo4j-fundamentals/summary.adoc
  asciidoc/courses/neo4j-fundamentals/summary.pdf
  asciidoc/emails/user-completed-course.adoc
  asciidoc/emails/user-enrolment-reminder.adoc
  package-lock.json
  package.json
  resources/css/summary.css
  src/app.ts
  src/commands/generate-pdfs.ts
  src/main.ts
  src/utils.ts
  views/summary.pug
Labels: enhancement, draft
