Repository neo4j-graphacademy/courses, pull requests merged in 2025-06, with the labels that each got.

#345 Docker updates & Devcontainer config
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.extend.yaml
  .devcontainer/post_attach.sh
  .devcontainer/post_create.sh
  .dockerignore
  .gitattributes
  .vscode/extensions.json
  Dockerfile
  README.adoc
  asciidoc/courses/neo4j-fundamentals/course.adoc
  docker-compose.yaml
  package-lock.json
  package.json
Labels: Ready

#348 Support multiple database providers
  asciidoc/courses/modeling-fundamentals/course.adoc
  src/constants.ts
  src/services/load/load-courses.ts
  src/services/load/tx.ts
Labels: release, Ready

#351 genai-fundamentals updates
  asciidoc/courses/genai-fundamentals/course.adoc
  asciidoc/courses/genai-fundamentals/modules/1-generative-ai/lessons/2-considerations/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/1-generative-ai/lessons/3-context/images/llm-prompt-document-results.svg
  asciidoc/courses/genai-fundamentals/modules/1-generative-ai/lessons/3-context/images/llm-prompt-document.svg
  asciidoc/courses/genai-fundamentals/modules/1-generative-ai/lessons/3-context/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/2-rag/lessons/4-graphrag/images/llm-text-to-cypher-process.svg
  asciidoc/courses/genai-fundamentals/modules/2-rag/lessons/4-graphrag/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/2-rag/module.adoc
  asciidoc/courses/genai-fundamentals/modules/3-knowledge-graphs/lessons/2-constructing-knowledge-graphs/images/unstructured-kg.json
  asciidoc/courses/genai-fundamentals/modules/3-knowledge-graphs/lessons/2-constructing-knowledge-graphs/images/unstructured-kg.svg
  asciidoc/courses/genai-fundamentals/modules/3-knowledge-graphs/lessons/2-constructing-knowledge-graphs/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/4-integrating-neo4j/lessons/4-vector-graph/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/4-integrating-neo4j/lessons/6-frameworks/lesson.adoc
Labels: draft

#356 Building your own MCP tools
  asciidoc/courses/genai-mcp-neo4j-tools/_move/3-building-mcp-tools-fastmcp/lessons/1-mcp-python-sdk/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/_move/3-building-mcp-tools-fastmcp/lessons/10c-integrated-workflow/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/_move/3-building-mcp-tools-fastmcp/lessons/2-introduction-to-fast-mcp/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/_move/3-building-mcp-tools-fastmcp/lessons/3-building-tools/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/_move/3-building-mcp-tools-fastmcp/lessons/4c-text-to-cypher-tool/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/_move/3-building-mcp-tools-fastmcp/lessons/5c-graph-resource/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/_move/3-building-mcp-tools-fastmcp/module.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/banner.png
  asciidoc/courses/genai-mcp-neo4j-tools/course.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/illustration.svg
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/1-getting-started/images/react-agent-diagram-v0.png
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/1-getting-started/images/react-agent-diagram.png
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/1-getting-started/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/2-pop-quiz/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/2-pop-quiz/questions/1-mcp-stands-for.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/2-pop-quiz/questions/2-role-of-servers.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/2-pop-quiz/questions/3-tool-definitions.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/3-installing-servers/includes/claude_desktop_config.json
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/3-installing-servers/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/4c-install-mcp-neo4j-cypher/images/chat-list-available-tools.jpg
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/4c-install-mcp-neo4j-cypher/images/mcp-list-servers.jpg
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/4c-install-mcp-neo4j-cypher/images/mcp-listed-servers.jpg
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/4c-install-mcp-neo4j-cypher/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/4c-install-mcp-neo4j-cypher/questions/1-tools-available.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/module.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/1-mcp-neo4j-cypher/images/agent-mode.png
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/1-mcp-neo4j-cypher/images/create-adam-conversation.png
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/1-mcp-neo4j-cypher/includes/schema.json
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/1-mcp-neo4j-cypher/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/1-mcp-neo4j-cypher/questions/1-tool-safety.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/2c-reading-graph-schema/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/2c-reading-graph-schema/questions/1-user-relationships.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/3c-generating-cypher-statements/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/3c-generating-cypher-statements/questions/1-highest-rated-movie.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/4c-build-application/includes/notes.txt
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/4c-build-application/includes/prompt.txt
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/4c-build-application/includes/solution.py
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/4c-build-application/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/4c-build-application/questions/1-application-results.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/5-summary/lesson.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/module.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/summary.adoc
  asciidoc/shared/courses/apps/sandbox-env.adoc
  public/img/courses/banners/genai-mcp-neo4j-tools.png
  public/img/courses/illustrations/genai-mcp-neo4j-tools.svg
  public/img/og/og-landing.png
  src/services/sync-categories.ts
Labels: draft, release

#361 Open chatbot on lesson load
  asciidoc/courses/genai-mcp-neo4j-tools/course.adoc
  asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/3-installing-servers/lesson.adoc
  src/constants.ts
  src/services/load/load-lessons.ts
  src/services/load/tx.ts
Labels: enhancement

#363 Add llms.txt
  .cursor/create-course-llmstxt.mdc
  .cursor/create-course-theory-llmstxt.mdc
  .cursor/review-course.mdc
  .cursor/review-lesson-content.mdc
  asciidoc/courses/drivers-java/llms.txt
  asciidoc/courses/drivers-java/slides.pdf
  asciidoc/courses/drivers-python/llms.txt
  asciidoc/courses/genai-mcp-neo4j-tools/llms.txt
  asciidoc/courses/importing-fundamentals/llms.txt
  asciidoc/courses/modeling-fundamentals/llms.txt
  asciidoc/courses/neo4j-fundamentals/llms.txt
  public/slides/drivers-java.pdf
  src/app.ts
Labels: enhancement
