Repository neo4j-graphacademy/courses, pull requests merged in 2025-08, with the labels that each got.

#380 replace certificate link with link to account
  asciidoc/shared/emails/share.adoc
Labels: enhancement, Ready

#378 Minor fixes
  asciidoc/courses/genai-mcp-build-custom-tools-python/course.adoc
  asciidoc/courses/genai-mcp-build-custom-tools-typescript/course.adoc
  asciidoc/courses/importing-cypher/modules/4-import-considerations/lessons/5-next-steps/lesson.adoc
  asciidoc/courses/importing-cypher/summary.adoc
  asciidoc/courses/importing-fundamentals/modules/1-importing-data/lessons/3-tools/lesson.adoc
  asciidoc/courses/importing-fundamentals/modules/2-data-importer/lessons/1-importing-nodes/lesson.adoc
  asciidoc/courses/importing-fundamentals/modules/2-data-importer/lessons/8-data-importer-considerations/lesson.adoc
  public/img/courses/shared/sandboxicon.svg
Labels: bug, Ready

#388 added additional context
  asciidoc/courses/workshop-genai/llms.txt
  asciidoc/courses/workshop-genai/modules/1-generative-ai/llms.txt
  asciidoc/courses/workshop-genai/modules/2-retrievers/llms.txt
  asciidoc/courses/workshop-genai/modules/3-agents/llms.txt
Labels: enhancement

#387 genai-fundamentals - edits and suggestions
  asciidoc/courses/genai-fundamentals/modules/1-generative-ai/lessons/1-what-is-genai/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/1-generative-ai/lessons/2-considerations/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/2-rag/lessons/1-what-is-rag/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/2-rag/lessons/2-vector-search/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/2-rag/lessons/4-graphrag/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/3-knowledge-graphs/lessons/1-what-is-a-knowledge-graph/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/3-knowledge-graphs/lessons/2-constructing-knowledge-graphs/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/4-integrating-neo4j/lessons/2-vector-retriever/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/4-integrating-neo4j/lessons/3-rag/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/4-integrating-neo4j/lessons/4-vector-graph/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/4-integrating-neo4j/lessons/5-text-to-cypher/lesson.adoc
  asciidoc/courses/genai-fundamentals/modules/4-integrating-neo4j/lessons/6-frameworks/lesson.adoc
Labels: Ready
